package com.cobblemoon.autoqiqi.battle;

import com.cobblemoon.autoqiqi.AutoQiqiClient;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * Loads Smogon OU usage stats from a bundled JSON resource and provides
 * lookup by species name. Data is generated by {@code tools/scrape_smogon.py}.
 * Uses Gen 9 OU which includes all Pokemon from every generation.
 *
 * <p>Usage:
 * <pre>
 *   SmogonData.load();                         // call once at mod init
 *   SmogonEntry entry = SmogonData.get("dragapult");
 *   entry.topMoves();                          // {dracometeor=45.1, shadowball=40.0, ...}
 *   entry.roles();                             // [CHOICE, REVENGE_KILLER, PIVOT]
 *   entry.likelyScarfUser();                   // true
 * </pre>
 */
public class SmogonData {
    private static final String RESOURCE_PATH = "/assets/auto-qiqi/smogon_ou.json";
    private static final Map<String, SmogonEntry> ENTRIES = new HashMap<>();
    private static boolean loaded = false;

    private SmogonData() {}

    public static void load() {
        if (loaded) return;
        try (InputStream is = SmogonData.class.getResourceAsStream(RESOURCE_PATH)) {
            if (is == null) {
                AutoQiqiClient.logDebug("Smogon", "Resource not found: " + RESOURCE_PATH);
                loaded = true;
                return;
            }
            JsonObject root = new Gson().fromJson(new InputStreamReader(is, StandardCharsets.UTF_8), JsonObject.class);
            JsonObject pokemon = root.getAsJsonObject("pokemon");
            if (pokemon == null) {
                loaded = true;
                return;
            }
            for (var entry : pokemon.entrySet()) {
                ENTRIES.put(entry.getKey(), parseEntry(entry.getValue().getAsJsonObject()));
            }
            AutoQiqiClient.logDebug("Smogon", "Loaded " + ENTRIES.size() + " Pokemon from Smogon OU stats");
        } catch (Exception e) {
            AutoQiqiClient.logDebug("Smogon", "Failed to load Smogon data: " + e.getMessage());
        }
        loaded = true;
    }

    /** Look up by normalized species name (lowercase, no special chars). */
    public static SmogonEntry get(String normalizedSpecies) {
        if (!loaded) load();
        if (normalizedSpecies == null) return null;
        return ENTRIES.get(normalizedSpecies.toLowerCase().replaceAll("[^a-z0-9]", ""));
    }

    /** Check if we have data for a species. */
    public static boolean has(String normalizedSpecies) {
        return get(normalizedSpecies) != null;
    }

    public static int size() {
        if (!loaded) load();
        return ENTRIES.size();
    }

    // ========================
    // Entry parsing
    // ========================

    private static SmogonEntry parseEntry(JsonObject obj) {
        String name = obj.has("name") ? obj.get("name").getAsString() : "?";

        List<String> roles = new ArrayList<>();
        if (obj.has("roles")) {
            for (JsonElement e : obj.getAsJsonArray("roles")) {
                roles.add(e.getAsString());
            }
        }

        LinkedHashMap<String, Double> moves = parsePercentMap(obj, "moves");
        LinkedHashMap<String, Double> items = parsePercentMap(obj, "items");
        LinkedHashMap<String, Double> abilities = parsePercentMap(obj, "abilities");

        List<String> teammates = new ArrayList<>();
        if (obj.has("teammates")) {
            for (JsonElement e : obj.getAsJsonArray("teammates")) {
                teammates.add(e.getAsString());
            }
        }

        List<SpreadInfo> spreads = new ArrayList<>();
        if (obj.has("spreads")) {
            for (JsonElement e : obj.getAsJsonArray("spreads")) {
                JsonObject s = e.getAsJsonObject();
                spreads.add(new SpreadInfo(
                        s.has("nature") ? s.get("nature").getAsString() : "Hardy",
                        getIntOr(s, "hp", 0), getIntOr(s, "atk", 0), getIntOr(s, "def", 0),
                        getIntOr(s, "spa", 0), getIntOr(s, "spd", 0), getIntOr(s, "spe", 0)
                ));
            }
        }

        SpeedInfo speed = null;
        if (obj.has("speed")) {
            JsonObject sp = obj.getAsJsonObject("speed");
            speed = new SpeedInfo(
                    sp.has("nature") ? sp.get("nature").getAsString() : "Hardy",
                    getIntOr(sp, "spe_ev", 0)
            );
        }

        return new SmogonEntry(name, roles, moves, items, abilities, teammates, spreads, speed);
    }

    private static LinkedHashMap<String, Double> parsePercentMap(JsonObject parent, String key) {
        LinkedHashMap<String, Double> map = new LinkedHashMap<>();
        if (!parent.has(key)) return map;
        JsonObject obj = parent.getAsJsonObject(key);
        obj.entrySet().stream()
                .sorted((a, b) -> Double.compare(b.getValue().getAsDouble(), a.getValue().getAsDouble()))
                .forEach(e -> map.put(e.getKey(), e.getValue().getAsDouble()));
        return map;
    }

    private static int getIntOr(JsonObject obj, String key, int def) {
        return obj.has(key) ? obj.get(key).getAsInt() : def;
    }

    // ========================
    // Data records
    // ========================

    public record SmogonEntry(
            String displayName,
            List<String> roles,
            LinkedHashMap<String, Double> moves,
            LinkedHashMap<String, Double> items,
            LinkedHashMap<String, Double> abilities,
            List<String> teammates,
            List<SpreadInfo> spreads,
            SpeedInfo speed
    ) {
        /** Top N moves by usage %. */
        public LinkedHashMap<String, Double> topMoves(int n) {
            LinkedHashMap<String, Double> top = new LinkedHashMap<>();
            int i = 0;
            for (var e : moves.entrySet()) {
                if (i++ >= n) break;
                top.put(e.getKey(), e.getValue());
            }
            return top;
        }

        /** Most common item name, or null. */
        public String likelyItem() {
            return items.isEmpty() ? null : items.keySet().iterator().next();
        }

        /** True if Choice Scarf is the most common item (>20% usage). */
        public boolean likelyScarfUser() {
            Double scarfPct = items.get("choicescarf");
            return scarfPct != null && scarfPct >= 20.0;
        }

        /** True if any Choice item is top item. */
        public boolean likelyChoiceLocked() {
            String top = likelyItem();
            return top != null && (top.equals("choicescarf") || top.equals("choiceband") || top.equals("choicespecs"));
        }

        /** True if this Pokemon commonly runs a specific move (by normalized name, >= threshold %). */
        public boolean commonlyRuns(String normalizedMove, double thresholdPct) {
            Double pct = moves.get(normalizedMove);
            return pct != null && pct >= thresholdPct;
        }

        /** Get coverage moves that hit a given set of types super-effectively. Returns move names. */
        public List<String> coverageMovesVs(List<String> defenderTypes, String defenderSpecies) {
            List<String> coverage = new ArrayList<>();
            for (String moveName : moves.keySet()) {
                var tpl = com.cobblemon.mod.common.api.moves.Moves.INSTANCE.getByName(moveName);
                if (tpl == null) continue;
                String moveType = tpl.getElementalType().getName().toLowerCase();
                double eff = TypeChart.getEffectiveness(moveType, defenderTypes, defenderSpecies);
                if (eff >= 2.0) {
                    coverage.add(moveName);
                }
            }
            return coverage;
        }

        /** Whether this Pokemon commonly uses the given speed nature (Jolly/Timid). */
        public boolean isCommonlyMaxSpeed() {
            return speed != null && speed.speEv >= 252
                    && (speed.nature.equals("Jolly") || speed.nature.equals("Timid"));
        }

        /** Format roles as a short display string: "SETUP / PIVOT" */
        public String rolesDisplay() {
            return String.join(" / ", roles);
        }

        /** Format top 4 moves as a display string for HUD. */
        public String movesDisplay() {
            StringBuilder sb = new StringBuilder();
            int i = 0;
            for (var e : moves.entrySet()) {
                if (i++ >= 4) break;
                if (!sb.isEmpty()) sb.append(", ");
                sb.append(localizeMoveName(e.getKey())).append(" ").append(String.format("%.0f%%", e.getValue()));
            }
            return sb.toString();
        }

        private static String localizeMoveName(String internalName) {
            String translated = net.minecraft.text.Text.translatable("cobblemon.move." + internalName).getString();
            return translated.startsWith("cobblemon.move.") ? internalName : translated;
        }

        /** Format likely item display. */
        public String itemDisplay() {
            if (items.isEmpty()) return "?";
            var first = items.entrySet().iterator().next();
            return first.getKey() + " " + String.format("%.0f%%", first.getValue());
        }
    }

    public record SpreadInfo(String nature, int hp, int atk, int def, int spa, int spd, int spe) {}

    public record SpeedInfo(String nature, int speEv) {}
}
